### PR TITLE
Create techcrunch.csv

### PR DESCRIPTION
**Pull request by kylestratis**
**How to merge your changes:** 

1. [Make sure the CI code style tests all pass.](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

### CODE REVIEW

**Comment by dbader** [comment]
Thanks Kyle—typo in the filename? `techcruch.csv`

**Comment by kylestratis** [comment]
Fixed, thanks @dbader

**Comment by dbader** [comment]
@kylestratis Cheers, does this need merging?

**Comment by kylestratis** [comment]
@dbader Yes please! The article itself is still waiting on didactic review so no huge rush!

**Comment by dbader** [comment]
Ok cool, LGTM. (Btw you can merge yourself after the PR changes have been approved, I'm just gonna go ahead and do it on this one)

**Pull request merged**
