### PR TITLE
Skeleton files for csv-interview article

### PR DESCRIPTION
**Pull request by jima80525**
**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

### CODE REVIEW

**Comment by dbader** [comment]
Thanks @jima80525! 

1. Can we rename the top-level folder for this from `python-interview-problems-parsing-csv-python-files` to `python-interview-problems-parsing-csv`?
2. There's a couple of linter issues flagged by CI that need resolving (if you want the unused import there you can add a ` # noqa` comment on that line to disable the flake8 check.)

**Comment by lpozo** [comment]
@jima80525 Thanks!

Since this is just a skeleton code, maybe we can comment the lines that break Black and add an additional comment with instructions on uncommenting the line before running the examples.

Also, I think that it'd be nice to have the full code for all the examples in a subdirectory. Then we can link to that at the end of the tutorial or so. We can probably have a skeleton_code/ directory and a full_code/ directory or something. What do you think?

**Comment by jima80525** [comment]
I'll get those changes in, but probably not tonight. It's looking like Saturday at this point. :)

**Comment by jima80525** [comment]
OK. Fixed up the linter issues and added the directory structure suggested by @lpozo  (great idea!)  Should be ready for re-review!

**Comment by lpozo** [comment]
Hey @jima80525 Great job!. I think I just have a final comment. It'd be beneficial to put the docstring describing the problem in the skeleton code files only. The test modules can have a generic docstring as they have now. For the next versions, we can probably add a comment at the top of the file with the section title and maybe the link to that section in the article. Other than that, this should be ready to move forward! Great to work with you again! Thanks!

**Pull request merged**
