### PR TITLE
Web scraping bs4

### PR DESCRIPTION
**Pull request by martin-martin**
**How to merge your changes:** 

1. [Make sure the CI code style tests all pass.](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

### CODE REVIEW

**Comment by martin-martin** [comment]
Code for Tutorial: https://realpython.com/scraping-websites-python-and-beautifulsoup/

**Comment by martin-martin** [comment]
Does that mean it's ok even though the check fails?

```
would reformat /home/circleci/repo/web-scraping-bs4/scrape_jobs.py
would reformat /home/circleci/repo/web-scraping-bs4/job_search.py
All done! 💥 💔 💥
```

**Comment by dbader** [comment]
@martin-martin It means that `black` requested formatting changes. You can apply them automatically by doing this: https://github.com/realpython/materials#running-python-code-formatter

**Comment by martin-martin** [comment]
Ran `black` and fixed it. Seems all checks are passing now.

**Comment by martin-martin** [comment]
Hei @dbader should I/can I merge the PR myself when it's been approved?

**Comment by dbader** [comment]
@martin-martin Yep merge away whenever :)

**Pull request merged**
