### PR TITLE
Location based web app geodjango

### PR DESCRIPTION
**Pull request by techiediaries**

### CODE REVIEW

**Comment by dbader** [comment]
Thanks for creating the PR @techiediaries. This is currently failing a bunch of style and linter checks, please see [the README](https://github.com/realpython/materials/blob/master/README.md). Once we've got that green checkmark from CircleCI we're ready to merge.

**Comment by techiediaries** [comment]
@dbader I used black to reformat the code but there are still 6 warnings about too long lines. This  example, in the `settings.py` file:

        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"

Locally black --check returns All done!

**Comment by dbader** [comment]
> @dbader I used black to reformat the code but there are still 6 warnings about too long lines. This example, in the `settings.py` file:

Cheers—those lines will need to be split manually to get the flake8 check to pass. Not sure why black doesn't do it automatically though.

**Comment by techiediaries** [comment]
There is still one failed check.

This line 
`                    location = fromstr(f'POINT({longitude} {latitude})',
                        srid=4326)`

Throws continuation line under-indented for visual indent or over-indented?

**Comment by dbader** [comment]
@techiediaries Alright let's merge it, I'll get it sorted out on master locally. The final thing we need to do is add a link from the article to the sample project here on GitHub :)

**Comment by techiediaries** [comment]
Ok I'll add it.

**Comment by dbader** [comment]
Thx Ahmed. If you're curious, this is what's fixed the linter complaint: https://github.com/realpython/materials/commit/c59a8722d821595547cbf18435b79a368931092a

**Comment by techiediaries** [comment]
Ok I didn't think of that :)

**Pull request merged**
