### PR TITLE
Qt Designer Sample Text Editor

### PR DESCRIPTION
**Pull request by lpozo**
**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

### CODE REVIEW

**Comment by bzaczynski** [comment]
@lpozo After following the steps from the README file, I can't see the icons:

sample_editor

**Comment by lpozo** [comment]
@bzaczynski I made some changes to solve this issue. Can you run the app again to see if it works now? Thanks in advance!

**Comment by bzaczynski** [comment]
@lpozo Okay, the icons are now visible. However, there's no `find_replace.ui` file in the `ui/` subfolder, so clicking on the _Edit | Find & Replace..._ fails with the following error:

```shell
$ python app.py
Traceback (most recent call last):
  File "/home/realpython/sample_editor/app.py", line 21, in findAndReplace
    dialog = FindReplaceDialog(self)
  File "/home/realpython/sample_editor/app.py", line 38, in __init__
    loadUi("ui/find_replace.ui", self)
  File "/home/realpython/sample_editor/venv/lib/python3.9/site-packages/PyQt5/uic/__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/home/realpython/sample_editor/venv/lib/python3.9/site-packages/PyQt5/uic/Loader/loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "/home/realpython/sample_editor/venv/lib/python3.9/site-packages/PyQt5/uic/uiparser.py", line 1020, in parse
    document = parse(filename)
  File "/home/realpython/.pyenv/versions/3.9.0/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/home/realpython/.pyenv/versions/3.9.0/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'ui/find_replace.ui'
Aborted (core dumped)
```

**Comment by lpozo** [comment]
Hey @bzaczynski, I pushed the `.ui` files. I have a `.gitignore_global` in my home directory that was causing those files to be ignored by git. Sorry about that. Thanks!

**Comment by bzaczynski** [comment]
@lpozo Thanks Leodanis. This looks good to me. We'll merge your PR later when Jacob makes his changes.

**Review by jaschmitt — APPROVED** [review]

**Pull request merged**
