### PR TITLE
Upgrade linters and switch to Ruff

### PR DESCRIPTION
**Pull request by gahjelle**
Upgrade the GitHub Action to use Python 3.12 and Black 24. Change linter from Flake8 to Ruff.

### CODE REVIEW

**Review by dbader — APPROVED** [review]
Thanks @gahjelle!

**Comment by dbader** [comment]
I've temporarily removed the branch protection rule @gahjelle so you can go ahead with the merge on Monday. Please send me a quick ping once that's done so I can bring back the new branch protection rule. (Or maybe you can do it as well).

**Comment by dbader** [comment]
@gahjelle Actually, scratch that. I misunderstood the branch protection rules UI and now I was able to add the new `Linux312` action as required. So we should be able to merge this PR.

**Comment by gahjelle** [comment]
Thanks @dbader 

I've merged this one and the new 3.12 action seems to work well.

**Pull request merged**
