### PR TITLE
Complete code for embedded Python article

### PR DESCRIPTION
**Pull request by notexactlyawe**
**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

### CODE REVIEW

**Comment by notexactlyawe** [comment]
Linter is failing because of the `from microbit import *`, however that's idiomatic when writing code for the micro:bit. See the [accelerometer examples in the docs](https://microbit-micropython.readthedocs.io/en/v1.0.1/accelerometer.html#examples) for an example.

**Comment by dbader** [comment]
Thanks @notexactlyawe -- I agree it makes sense to keep the wildcard around in this case. To pass the linter check, you can add a `# noqa` comment on the affected line:

```python
from microbit import *  # noqa
from random import randrange
...
```

**Comment by notexactlyawe** [comment]
Thanks @dbader. It looks like that fixes the error on line 1 but not the other errors that come when I use modules/functions from `microbit`. I can:
 - Add `noqa` comments to all affected lines
 - Add a file-level noqa (which would squash any other errors that appear if we change this file)
 - Ignore the CI errors

Do you have a preferred fix?

**Comment by dbader** [comment]
Hmm...so, thinking about this again, maybe it would actually be better to not do the wildcard import then. Sure it's what the microbit docs do, but there should be no downside/difference to using named imports. And it would clean up the code...

**Comment by notexactlyawe** [comment]
Thanks @dbader, I've expanded the import and the linter is passing now. I'll come back and update the README when we have a finalized title and link to the article.

**Comment by bzaczynski** [comment]
lgtm

**Review by jaschmitt — APPROVED** [review]
Changes implemented by author

**Pull request merged**
