### PR TITLE
Python Dash tutorial resources

### PR DESCRIPTION
**Pull request by dylanjcastillo**
**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

### CODE REVIEW

**Review by somacdivad — APPROVED** [review]
Approving this :smile: Everything looks good and matches what we've got in the article!

**Comment by dylanjcastillo** [comment]
Hi @somacdivad, these are the changes requested by Jacob. I'm waiting for his confirmation to commit the article's changes. 

I made the changes on top of the last version of the tutorial in the CMS, which contains some of the Language Edit modifications. So I wanted to confirm if he wanted me to do the commit or if he's planning on doing it himself.

**Review by somacdivad — APPROVED** [review]
Changes look good to me @dylanjcastillo and @jaschmitt!

**Comment by dylanjcastillo** [comment]
Hi @somacdivad @jaschmitt, I noticed the black check was failing and fixed it (I had the wrong default for line length).

**Comment by jaschmitt** [comment]
Thanks, @dylanjcastillo!

**Pull request merged**
