### PR TITLE
Materials for Consuming APIs article

### PR DESCRIPTION
**Pull request by pedropregueiro**
**Where to put new files:**

- New files should go into a top-level subfolder, named after the article slug. For example: `my-awesome-article`

**How to merge your changes:** 

1. [Make sure the CI code style tests all pass (+ run the automatic code formatter if necessary).](https://github.com/realpython/materials/blob/master/README.md)
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

### CODE REVIEW

**Review by JFincher42 — CHANGES_REQUESTED** [review]
Hi Pedro:

I checked all the code, and it works great!

While I don't have anything specific to call out in any of these programs, I have some overall observations I'd like you to consider before checking in:

- All of the code needs comments, especially when you are importing libraries other than `requests`. I would also add them for each meaningful block of code.
- You should use f-strings for your output formatting.
- For data like API keys or client keys which the reader should be replacing, your comment should be more noticeable. I would capitalize part of it to draw attention to it.

The GitHub code is a great example of all these. Comments can help explain why there are three different helper functions. All the output is more understandable when formatted with f-strings as well. And since the user needs to get an API key and take some action, those areas should be more noticeable.

Look forward to the next iteration!

--Jon

**Comment by pedropregueiro** [comment]
This one is ready for another pass @JFincher42.

**Comment by pedropregueiro** [comment]
Fixed all remaining linting issues.

**Review by JFincher42 — APPROVED** [review]
Love the changes - ship it!

**Pull request merged**
