### PR TITLE
Understanding async python

### PR DESCRIPTION
**Pull request by writeson**
**How to merge your changes:** 

1. Make sure the CI code style tests all pass. 
2. Find an RP Team member on Slack and ask them to review & approve your PR.
3. Once the PR has one positive ("approved") review, GitHub lets you merge the PR.
4. 🎉

### CODE REVIEW

**Comment by writeson** [comment]
Hi Dan, not sure what ci/circleci is trying to tell me about my code failing tests. Can you help me out?

**Comment by dbader** [comment]
> Hi Dan, not sure what ci/circleci is trying to tell me about my code failing tests. Can you help me out?

Hi @writeson, we're using a tool called *Black* on this repo to ensure consistent formatting. On CI it runs in "check" mode to ensure any new files added to the repo are following PEP 8.

The easiest way to resolve these errors is to just run Black locally on the code and then committing those changes. There's a section in the README that shows you how to do that:

https://github.com/realpython/materials#running-python-code-formatter

**Comment by dbader** [comment]
@writeson Quick heads up, there are a bunch of binary files and other stuff from your local Python install in this PR that shouldn't be there. The materials repo should only include the sample code for the app, not the Python virtual environment.

**Comment by dbader** [comment]
@writeson  Quick heads up, I just pulled in the latest changes from master to get this in sync with some black/flake8 config changes I made :)

**Comment by dbader** [comment]
Please note that while this lints cleanly now those extra files still need to be removed before we can merge.

**Comment by dbader** [comment]
`understanding_asynchronous_programming` -> FYI the folder names should use dashes `-` to be consistent with all the other projects listed at https://github.com/realpython/materials/

**Comment by dbader** [comment]
@writeson Thanks for making those changes but there's still unrelated stuff from your venv in there, like this file: `/bin/activate`

Also we already have a `.gitignore` file in the root folder: https://github.com/realpython/materials/blob/master/.gitignore

So it shouldn't be necessary to add another one for this project. It just makes things more confusing in my experience to have multiple .gitignores floating around :)

**Comment by dbader** [comment]
@writeson Just checking in, looks like there's still parts of your venv committed on this branch, for example the `bin/activate` script. Once you remove those so that only the actual project source code remains we're ready to merge :)

**Comment by writeson** [comment]
Hi Dan,

I thought I took care of this, guess I'm confused how to get the venv
directory out of the repository. What's your suggestion?

Thanks!
Doug

**Comment by dbader** [comment]
No problem @writeson, I've removed the extra files. This is now ready to merge.

**Comment by writeson** [comment]
Thanks Dan, much appreciated!

**Pull request merged**
